# Site settings
title: HackOregon Guides
email: hello@hackoregon.org
description: > # this means to ignore newlines until "baseurl:"
  A repository for HackOregon best practices and general information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackoregon.github.io" # the base hostname & protocol for your site
twitter_username: HackOregon
github_username:  HackOregon

# Build settings
markdown: kramdown
